### ISSUE TITLE
Peer Feedback!

### ISSUE THREAD

**Issue by jraza19** [UBC-MDS/obesity-explorer-R#1]
https://github.com/UBC-MDS/dsci-532_group_02

Group 2: Ela Bandari, Ling (Elina) Lin, Kangbo Lu, Rachel Xu
foundation-product-dashboard.herokuapp.com

**Comment by tanmaysharma19** [comment]
Here is a link to the peer feedback we provided to Group-1.
https://github.com/UBC-MDS/dsci-532_group_02/issues/28
