### ISSUE TITLE
Addressing missing countries

### ISSUE THREAD

**Issue by jraza19** [UBC-MDS/obesity-explorer-R#24]

**Comment by rtaph** [comment]
Countries:
- South Sudan
- Cote d’Ivoire.
- Eritrea
- Northern portion of Somalia.
- North Korea
- Kosovo
- Greenland
- Taiwan

Most of these are likely because of missing data in the obesity data. It would be good to add an "About this Dashboard" tab for users to explain why certain geographic zones are missing.

**Comment by dusty736** [comment]
Initial Notes:

- South Sudan: No obesity data available in obesity_combo.csv
- Cote d’Ivoire: No obesity data available in obesity_combo.csv (Name character issue?)
- Eritrea: Data available, renders in plots.R but not dashboard.
- North Korea: No obesity data available in obesity_combo.csv (Name?  People's republic of Korea?)
- Kosovo: No obesity data available in obesity_combo.csv
- Greenland: No obesity data available in obesity_combo.csv.  (Included in Denmark?)
- Taiwan : No obesity data available in obesity_combo.csv.  (Related to China?  Included?)

Questions to investigate:
- Eritrea has data, and shows up in the plots in R but not app.  Needs further investigation.
- Many countries above aren't included in obesity_combo.csv.  Is obesity_combo.csv directly from the world bank?  One possible issue could be naming conventions if merging happened.
- First thoughts on possible reasons why countries were excluded listed above.

Solutions:
-Map correct names?

**Comment by dusty736** [comment]
Notes: 2/3/2021
- North Korea: Special character, join issue
- Cote d'Ivoire: Special character, join issue
- South Sudan: NA
- Kosovo: NA
- Taiwan: NA
- Greenland: NA
- Eretria:

**Comment by tanmaysharma19** [comment]
Addressed most in #59. Eretria still pending.
