### ISSUE TITLE
Smoking rate is missing from some years

### ISSUE THREAD

**Issue by jraza19** [UBC-MDS/obesity-explorer-R#26]

**Comment by jraza19** [comment]
After review of the data, I went ahead and I added a flag for missing values. Less than 10% of the data is actually there. Once I transform into rates, some rates end up being higher then 1000% - thinking its because of the way the fill works. Will keep trying. 

![image](https://user-images.githubusercontent.com/70663258/106558465-a3473b00-64d8-11eb-8554-f7d6de3cd5e0.png)
![image](https://user-images.githubusercontent.com/70663258/106559860-e60a1280-64da-11eb-9a98-976355883429.png)

**Comment by rtaph** [comment]
Thanks @jraza19 ! 10% data is not great, but I suppose that's all we have to work with.

Do you have this on a branch on your fork? Maybe we can take a look at the code see if we can't help.

**Comment by jraza19** [comment]
Thanks @rtaph for the help yesterday! The smoke data is filled and is displaying the correct rates for across years. When user selects this variable, a note is displayed to let them know about the reliability of this data. See related [PR ](https://github.com/UBC-MDS/obesity-explorer-R/pull/55)here. 


<img width="800" alt="Screen Shot 2021-02-02 at 7 39 25 PM" src="https://user-images.githubusercontent.com/70663258/106695391-596d5c00-658f-11eb-8313-5bc2330e36f3.png">
