### ISSUE TITLE
Meeting Minutes - Week 4

### ISSUE THREAD

**Issue by rtaph** [UBC-MDS/obesity-explorer-R#32]
Minutes:
2021-02-01, 2pm, Zoom.

Team reflections:
- Javairia: 
	- Continue working with the R app since it is more mature and documented.
	- Group dynamics were good
	- Appreciates that everyone dedicates their Friday to work on this
- Dustin:
	- Group dynamics continued to work well
	- Everyone showed up to meetings prepared
	- We always have a game plan
	- We finished our target deadlines
	- Very supporting group
	- Everyone has really great ideas
- Tanmay:
	- More than satisfied with our performance
	- Pretty much done by Friday night
	- Seems everyone is supporting each other with the workload
- Rafael:
	- Everyone has really good work habits
	- Like our collaboration planning

Game plan:
- Early / Today
	- Deploy to new Heroku server
	- All change our remotes for “Heroku” to avoid over-writing
	- Attempt the extra step of PR auto-deployment
	- Peer feedback
	- TA feedback
	- Github actions for automatic linting
	- Add dashboard name (__name__)
- Mid-Week
	- Aesthetics: 
		- Sizing
	- Remove some options in Plotly that don’t do anything
	- Addressing our known bugs and feature improvements from Milestone 3
- Late

- Joel’s feedback:
	- Likes the moves to tabs
	- Likes separation between global and local controls
	- Colour palette background, choose either grey or white (consistency)
	- Nothing major in terms of look and feel
	- Make the first tab fit without scrolling¬¬
	- Try having tabs loaded on demand

- Feedback from Chris¬¬¬:
	- Keep the scale constant between years
	- Make trendline thinner
	- Not super clear what the black line is
	- Dropdown padding on bottom
	- Smoking data missing
	- Put year in title for associations

**Comment by dusty736** [comment]
2021-02-03, 6pm, Zoom.

Added to list of things to do:
- Add devtools so Heroku will deploy.

**Comment by rtaph** [comment]
Meeting from 2021-02-03

Dustin:
-	Has investigated missingness in country map (see issue)
-	Was able to add a title
-	Still needs some work
- 
Javairia:
-	Went through the smoke data, fixed the issue of missing data by imputing (filling) records
-	Added a note below the dropdown to caution users if smoking is selected
-	Managed to remove the plotly controls (still needs a PR for it)
-	Finished most of the tasks
- 
Tanmay:
-	Most of the small fixes should be fine, will send PR tonight
-	Trying make headway for wrapping plots inside of cards

Raf
-	Bundled functionality into an R package structure
-	Added several Github Actions
