### ISSUE TITLE
Attempt to reduce latency by having plots load on demand

### ISSUE THREAD

**Issue by rtaph** [UBC-MDS/obesity-explorer-R#44]
In particular, avoid loading plots in other tabs that are hidden in order to speed up the app.

**Comment by jraza19** [comment]
In testing the app, the team felt that the user interface was not prohibitively slow. Furthermore, the team reflected on the fact that users would switch between tabs and preloading would be a beneficial experience. Finally, the memoization helped improved the responsiveness.
