### ISSUE TITLE
Local Dropdowns Squished to Bottom of Screen

### ISSUE THREAD

**Issue by rtaph** [UBC-MDS/obesity-explorer-R#46]
Would be nice to have some padding to let the app breathe.

**Comment by rtaph** [comment]
Have been modifying the padding/margin of multiple CSS classes without success. I don't think the `.Select-menu-outer` respects the bounds of the box it is in. May seek help on this.

**Comment by dusty736** [comment]
Adjusting the padding/margin did not fix the issue of the dropdown menu.  As is, all dropdown options are available for selection, and thus we determined it was fine as is.
