### ISSUE TITLE
Write Unit Tests

### ISSUE THREAD

**Issue by rtaph** [UBC-MDS/obesity-explorer-R#51]

**Comment by rtaph** [comment]
Javairia
- [ ] `rate()`

Rafael 
- [x] `remap_sex()`: See #54 
- [ ] Visual regression tests for plots (might be hard-- time allowing!)

Dustin
- [ ] `make_rate_data()`

Tanmay
- [x] `create_label()`

**Comment by tanmaysharma19** [comment]
Addressed in #73. Completed tests for all essential functions.
